In [3]:
!pip install numpy

import numpy as np



[notice] A new release of pip available: 22.3.1 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


ModuleNotFoundError: No module named 'numpy'

In [3]:
import numpy as np

A = [[1, 1], [0, 1]]
A1 = np.array(A)
np.matmul(A1, A1.transpose())

array([[2, 1],
       [1, 1]])

In [12]:
A=np.array([[2,2,0],[-1,1,-1]]).transpose()
x=np.array([[5,-5,2]]).transpose()
t1=np.matmul(A.transpose(), x)
t1
t2=np.linalg.inv(np.matmul(A.transpose(),A))
t2
t3=np.matmul(t2, t1)
t3
np.matmul(A, t3)

array([[ 4.],
       [-4.],
       [ 4.]])

In [8]:
A

array([[ 2, -1],
       [ 2,  1],
       [ 0, -1]])

In [22]:
aa = [[-2, -2, 1, 0], [-1, 2, 2, -1] ]
ba = [[1, 2, -3, -3]]
b = np.array(ba).transpose()
A = np.array(aa).transpose()
k = np.matmul(A.transpose(), A)
print(k)
t1 = np.matmul(A.transpose(), b)
d = np.linalg.inv(k)
t2 = np.matmul(d, t1)
t3 = np.matmul(A, t2)
t3
print(b - t3)

[[ 9  0]
 [ 0 10]]
[[-1.]
 [ 0.]
 [-2.]
 [-3.]]
